In [113]:
import os
import string
import pandas as pd
import numpy as np
import datetime

from sklearn.preprocessing import OneHotEncoder
# set printing all columns
pd.set_option('display.max_columns', None)

In [271]:
BPI_dt = pd.read_csv("../data/sepsis_cases_4.csv", sep=";")

In [209]:
# BPI15 
#Convert numeric strings, leave others as-is 
Responsible_actor = pd.to_numeric(BPI_dt['Responsible_actor'], errors='coerce')  # '193.0'→193.0, 'other'→NaN
BPI_dt['Responsible_actor'] = np.where(
    Responsible_actor.notna(), 
    Responsible_actor.astype('Int64').astype(str),  # Convert valid numbers to int strings
    BPI_dt['Responsible_actor']                         # Keep non-numeric strings
)

In [272]:
BPI_dt.head()

,Diagnose,DiagnosticArtAstrup,DiagnosticBlood,DiagnosticECG,DiagnosticIC,DiagnosticLacticAcid,DiagnosticLiquor,DiagnosticOther,DiagnosticSputum,DiagnosticUrinaryCulture,DiagnosticUrinarySediment,DiagnosticXthorax,DisfuncOrg,Hypotensie,Hypoxie,InfectionSuspected,Infusion,Oligurie,SIRSCritHeartRate,SIRSCritLeucos,SIRSCritTachypnea,SIRSCritTemperature,SIRSCriteria2OrMore,Age,Case ID,Activity,org:group,CRP,LacticAcid,Leucocytes,time:timestamp,timesincemidnight,month,weekday,hour,timesincelastevent,timesincecasestart,event_nr,open_cases,label
0,A,True,True,True,True,True,False,False,False,True,True,True,True,True,False,True,True,False,True,False,True,True,True,85.0,A,ER Registration,A,0.0,0.0,0.0,2014-10-22 09:15:41,555,10,2,9,0.000000,0.000000,1,81,deviant
1,A,True,True,True,True,True,False,False,False,True,True,True,True,True,False,True,True,False,True,False,True,True,True,85.0,A,Leucocytes,B,0.0,0.0,9.6,2014-10-22 09:27:00,567,10,2,9,0.000000,11.316667,2,81,deviant
2,A,True,True,True,True,True,False,False,False,True,True,True,True,True,False,True,True,False,True,False,True,True,True,85.0,A,CRP,B,21.0,0.0,9.6,2014-10-22 09:27:00,567,10,2,9,0.000000,11.316667,3,81,deviant
3,A,True,True,True,True,True,False,False,False,True,True,True,True,True,False,True,True,False,True,False,True,True,True,85.0,A,LacticAcid,B,21.0,2.2,9.6,2014-10-22 09:27:00,567,10,2,9,11.316667,11.316667,4,81,deviant
4,A,True,True,True,True,True,False,False,False,True,True,True,True,True,False,True,True,False,True,False,True,True,True,85.0,A,ER Triage,C,21.0,2.2,9.6,2014-10-22 09:33:37,573,10,2,9,6.616667,17.933333,5,81,deviant

In [273]:
BPI_dt.columns

Index(['Diagnose', 'DiagnosticArtAstrup', 'DiagnosticBlood', 'DiagnosticECG',
       'DiagnosticIC', 'DiagnosticLacticAcid', 'DiagnosticLiquor',
       'DiagnosticOther', 'DiagnosticSputum', 'DiagnosticUrinaryCulture',
       'DiagnosticUrinarySediment', 'DiagnosticXthorax', 'DisfuncOrg',
       'Hypotensie', 'Hypoxie', 'InfectionSuspected', 'Infusion', 'Oligurie',
       'SIRSCritHeartRate', 'SIRSCritLeucos', 'SIRSCritTachypnea',
       'SIRSCritTemperature', 'SIRSCriteria2OrMore', 'Age', 'Case ID',
       'Activity', 'org:group', 'CRP', 'LacticAcid', 'Leucocytes',
       'time:timestamp', 'timesincemidnight', 'month', 'weekday', 'hour',
       'timesincelastevent', 'timesincecasestart', 'event_nr', 'open_cases',
       'label'],
      dtype='object')

In [274]:
#traffice_fine set
BPI_dt = BPI_dt.drop(columns = ['timesincemidnight', 'month', 'weekday', 'hour','timesincelastevent', 'timesincecasestart', 'event_nr', 'open_cases'])

In [275]:
#check Nan 
BPI_dt.isna().any()

Diagnose                     False
DiagnosticArtAstrup          False
DiagnosticBlood              False
DiagnosticECG                False
DiagnosticIC                 False
DiagnosticLacticAcid         False
DiagnosticLiquor             False
DiagnosticOther              False
DiagnosticSputum             False
DiagnosticUrinaryCulture     False
DiagnosticUrinarySediment    False
DiagnosticXthorax            False
DisfuncOrg                   False
Hypotensie                   False
Hypoxie                      False
InfectionSuspected           False
Infusion                     False
Oligurie                     False
SIRSCritHeartRate            False
SIRSCritLeucos               False
SIRSCritTachypnea            False
SIRSCritTemperature          False
SIRSCriteria2OrMore          False
Age                          False
Case ID                      False
Activity                     False
org:group                    False
CRP                          False
LacticAcid                   False
Leucocytes                   False
time:timestamp               False
label                        False
dtype: bool

In [276]:
BPI_dt.dtypes

Diagnose                      object
DiagnosticArtAstrup           object
DiagnosticBlood               object
DiagnosticECG                 object
DiagnosticIC                  object
DiagnosticLacticAcid          object
DiagnosticLiquor              object
DiagnosticOther               object
DiagnosticSputum              object
DiagnosticUrinaryCulture      object
DiagnosticUrinarySediment     object
DiagnosticXthorax             object
DisfuncOrg                    object
Hypotensie                    object
Hypoxie                       object
InfectionSuspected            object
Infusion                      object
Oligurie                      object
SIRSCritHeartRate             object
SIRSCritLeucos                object
SIRSCritTachypnea             object
SIRSCritTemperature           object
SIRSCriteria2OrMore           object
Age                          float64
Case ID                       object
Activity                      object
org:group                     object
CRP                          float64
LacticAcid                   float64
Leucocytes                   float64
time:timestamp                object
label                         object
dtype: object

In [277]:
# Drop columns where all values equal the first row's value
BPI_dt = BPI_dt.loc[:, ~BPI_dt.apply(lambda x: (x == x.iloc[0]).all())]

In [278]:
# Sort by case and time to ensure the starts come before completes for the same event
#BPI_dt.sort_values(by=['Case ID', 'Complete Timestamp'], inplace=True)
#BPI_dt['Case ID'] = BPI_dt['Case ID'].astype(str)
#BPI_dt['org:resource'] = BPI_dt['org:resource'].astype(str)
BPI_dt.sort_values(by=['Case ID', 'time:timestamp'], inplace=True)

In [279]:
# Drop repeated rows and reset index
BPI_dt = BPI_dt.drop_duplicates().reset_index(drop=True)

In [280]:
BPI_dt.head()

,Diagnose,DiagnosticArtAstrup,DiagnosticBlood,DiagnosticECG,DiagnosticIC,DiagnosticLacticAcid,DiagnosticLiquor,DiagnosticOther,DiagnosticSputum,DiagnosticUrinaryCulture,DiagnosticUrinarySediment,DiagnosticXthorax,DisfuncOrg,Hypotensie,Hypoxie,InfectionSuspected,Infusion,Oligurie,SIRSCritHeartRate,SIRSCritLeucos,SIRSCritTachypnea,SIRSCritTemperature,SIRSCriteria2OrMore,Age,Case ID,Activity,org:group,CRP,LacticAcid,Leucocytes,time:timestamp,label
0,A,True,True,True,True,True,False,False,False,True,True,True,True,True,False,True,True,False,True,False,True,True,True,85.0,A,ER Registration,A,0.0,0.0,0.0,2014-10-22 09:15:41,deviant
1,A,True,True,True,True,True,False,False,False,True,True,True,True,True,False,True,True,False,True,False,True,True,True,85.0,A,Leucocytes,B,0.0,0.0,9.6,2014-10-22 09:27:00,deviant
2,A,True,True,True,True,True,False,False,False,True,True,True,True,True,False,True,True,False,True,False,True,True,True,85.0,A,CRP,B,21.0,0.0,9.6,2014-10-22 09:27:00,deviant
3,A,True,True,True,True,True,False,False,False,True,True,True,True,True,False,True,True,False,True,False,True,True,True,85.0,A,LacticAcid,B,21.0,2.2,9.6,2014-10-22 09:27:00,deviant
4,A,True,True,True,True,True,False,False,False,True,True,True,True,True,False,True,True,False,True,False,True,True,True,85.0,A,ER Triage,C,21.0,2.2,9.6,2014-10-22 09:33:37,deviant

In [281]:
def generate_labels(n):
    from itertools import product
    import string

    chars = string.ascii_uppercase
    # 1-letter + 2-letter combos (up to 702 labels)
    labels = list(chars) + [''.join(p) for p in product(chars, repeat=2)]
    if n > len(labels):
        raise ValueError("Too many activities. Extend to 3-letter if needed.")
    return labels[:n]

activities = sorted(BPI_dt['Activity'].unique())
labels = generate_labels(len(activities))
activity_mapping = dict(zip(activities, labels))

In [282]:
activity_mapping

{'Admission IC': 'A',
 'Admission NC': 'B',
 'CRP': 'C',
 'ER Registration': 'D',
 'ER Sepsis Triage': 'E',
 'ER Triage': 'F',
 'IV Antibiotics': 'G',
 'IV Liquid': 'H',
 'LacticAcid': 'I',
 'Leucocytes': 'J',
 'Release B': 'K',
 'Release C': 'L',
 'Release D': 'M',
 'Return ER': 'N',
 'other': 'O'}

In [283]:
# Apply the mappings to create the new columns in 'bpi12_DT'
#BPI12/17 set
#BPI_dt['event_label'] = BPI12_dt['pre_concept:name'] + BPI12_dt['concept:name'].map(activity_mapping)
#traffic_fine
BPI_dt['event'] = BPI_dt['Activity'].map(activity_mapping)

In [284]:
#BPI_dt['Complete Timestamp'] = pd.to_datetime(BPI_dt['Complete Timestamp'], format='ISO8601').dt.strftime('%Y-%m-%d %H:%M:%S')
BPI_dt['time:timestamp'] = pd.to_datetime(BPI_dt['time:timestamp'], format='ISO8601').dt.strftime('%Y-%m-%d %H:%M:%S')

In [285]:
#BPI_dt.rename(columns={"Complete Timestamp": "time", "Case ID": "sequence", "label": "result"}, inplace=True)
BPI_dt.rename(columns={"time:timestamp": "time", "Case ID": "sequence", "label": "result"}, inplace=True)

In [286]:
BPI_dt.head()

,Diagnose,DiagnosticArtAstrup,DiagnosticBlood,DiagnosticECG,DiagnosticIC,DiagnosticLacticAcid,DiagnosticLiquor,DiagnosticOther,DiagnosticSputum,DiagnosticUrinaryCulture,DiagnosticUrinarySediment,DiagnosticXthorax,DisfuncOrg,Hypotensie,Hypoxie,InfectionSuspected,Infusion,Oligurie,SIRSCritHeartRate,SIRSCritLeucos,SIRSCritTachypnea,SIRSCritTemperature,SIRSCriteria2OrMore,Age,sequence,Activity,org:group,CRP,LacticAcid,Leucocytes,time,result,event
0,A,True,True,True,True,True,False,False,False,True,True,True,True,True,False,True,True,False,True,False,True,True,True,85.0,A,ER Registration,A,0.0,0.0,0.0,2014-10-22 09:15:41,deviant,D
1,A,True,True,True,True,True,False,False,False,True,True,True,True,True,False,True,True,False,True,False,True,True,True,85.0,A,Leucocytes,B,0.0,0.0,9.6,2014-10-22 09:27:00,deviant,J
2,A,True,True,True,True,True,False,False,False,True,True,True,True,True,False,True,True,False,True,False,True,True,True,85.0,A,CRP,B,21.0,0.0,9.6,2014-10-22 09:27:00,deviant,C
3,A,True,True,True,True,True,False,False,False,True,True,True,True,True,False,True,True,False,True,False,True,True,True,85.0,A,LacticAcid,B,21.0,2.2,9.6,2014-10-22 09:27:00,deviant,I
4,A,True,True,True,True,True,False,False,False,True,True,True,True,True,False,True,True,False,True,False,True,True,True,85.0,A,ER Triage,C,21.0,2.2,9.6,2014-10-22 09:33:37,deviant,F

In [287]:
BPI_dt = BPI_dt.drop(columns = ['Activity'])

In [288]:
def classify_and_rename(df, sequence_col, event_col, ex_col, unique_threshold = 1, manual_override = None):
    """
    Classifies attributes as sequence-level or event-level, detects categorical vs. numerical data, and renames columns.

    Parameters:
    - df (pd.DataFrame): The input DataFrame.
    - sequence_col (str): The column representing the sequence identifier.
    - event_col (str): The column representing the event identifier.
    - ex_col(list): The column representing the non atrribute columns.
    - unique_threshold (int, optional): Max unique values for numeric attributes to be considered categorical.
    - manual_override (list, optional): User-defined category overrides [col_name].

    Returns:
    - pd.DataFrame: DataFrame with renamed columns.
    - dict: Mapping of old column names to new ones.
    """

    # Exclude sequence & event columns from classification
    attribute_cols = [col for col in df.columns if col not in [sequence_col, event_col] + ex_col]

    sequence_level, event_level = [], []

    # Identify Sequence-Level vs. Event-Level
    for col in attribute_cols:
        if df.groupby(sequence_col)[col].nunique().max() == 1:
            sequence_level.append(col)
        else:
            event_level.append(col)

    def detect_categorical(columns):
        categorical, numerical = [], []
        for col in columns:
            if df[col].dtype == "object":
                categorical.append(col)
            elif df[col].dtype in ["int64", "float64", 'int32','float32']:
                if df[col].nunique() <= unique_threshold:
                    categorical.append(col)
                else:
                    numerical.append(col)
        return categorical, numerical

    # Auto-Detect Categorical vs. Numerical
    sequence_categorical, sequence_numerical = detect_categorical(sequence_level)
    event_categorical, event_numerical = detect_categorical(event_level)

    # Manual Override (if provided)
    if manual_override:
        for col in manual_override:
            if col in sequence_numerical:
                sequence_categorical.append(col)
                sequence_numerical.remove(col) 
            elif col in event_numerical:
                event_categorical.append(col)
                event_numerical.remove(col)
                
    print("Sequence-level attributes:", sequence_level)
    print("Event-level attributes:", event_level)

    # Step 4: Rename Columns
    new_column_names = {}

    for i, col in enumerate(sequence_categorical, start=1):
        new_column_names[col] = f"sc{i}"
    for i, col in enumerate(sequence_numerical, start=1):
        new_column_names[col] = f"sn{i}"
    for i, col in enumerate(event_categorical, start=1):
        new_column_names[col] = f"ec{i}"
    for i, col in enumerate(event_numerical, start=1):
        new_column_names[col] = f"en{i}"

    # Apply renaming
    df.rename(columns=new_column_names, inplace=True)

    return df, new_column_names

In [289]:
df, renamed_columns = classify_and_rename(BPI_dt, 
                                          sequence_col = "sequence", 
                                          event_col = "event", 
                                          ex_col = ['result', 'time'] #, 
                                          #manual_override = ['case:variant-index']
                                         )

print("Renamed Columns:", renamed_columns)

Sequence-level attributes: ['Diagnose', 'Age']
Event-level attributes: ['DiagnosticArtAstrup', 'DiagnosticBlood', 'DiagnosticECG', 'DiagnosticIC', 'DiagnosticLacticAcid', 'DiagnosticLiquor', 'DiagnosticOther', 'DiagnosticSputum', 'DiagnosticUrinaryCulture', 'DiagnosticUrinarySediment', 'DiagnosticXthorax', 'DisfuncOrg', 'Hypotensie', 'Hypoxie', 'InfectionSuspected', 'Infusion', 'Oligurie', 'SIRSCritHeartRate', 'SIRSCritLeucos', 'SIRSCritTachypnea', 'SIRSCritTemperature', 'SIRSCriteria2OrMore', 'org:group', 'CRP', 'LacticAcid', 'Leucocytes']
Renamed Columns: {'Diagnose': 'sc1', 'Age': 'sn1', 'DiagnosticArtAstrup': 'ec1', 'DiagnosticBlood': 'ec2', 'DiagnosticECG': 'ec3', 'DiagnosticIC': 'ec4', 'DiagnosticLacticAcid': 'ec5', 'DiagnosticLiquor': 'ec6', 'DiagnosticOther': 'ec7', 'DiagnosticSputum': 'ec8', 'DiagnosticUrinaryCulture': 'ec9', 'DiagnosticUrinarySediment': 'ec10', 'DiagnosticXthorax': 'ec11', 'DisfuncOrg': 'ec12', 'Hypotensie': 'ec13', 'Hypoxie': 'ec14', 'InfectionSuspected': 'ec15', 'Infusion': 'ec16', 'Oligurie': 'ec17', 'SIRSCritHeartRate': 'ec18', 'SIRSCritLeucos': 'ec19', 'SIRSCritTachypnea': 'ec20', 'SIRSCritTemperature': 'ec21', 'SIRSCriteria2OrMore': 'ec22', 'org:group': 'ec23', 'CRP': 'en1', 'LacticAcid': 'en2', 'Leucocytes': 'en3'}

In [290]:
# Drop columns where all values equal the first row's value
df = df.loc[:, ~df.apply(lambda x: (x == x.iloc[0]).all())]

In [291]:
import hashlib

def hash_col(col):
    return pd.util.hash_pandas_object(col, index=False).values.tobytes()

# Compute hash for each column
col_hashes = {col: hashlib.md5(hash_col(df[col])).hexdigest() for col in df.columns}

# Drop duplicate columns by hash
seen = set()
unique_cols = []
for col, h in col_hashes.items():
    if h not in seen:
        seen.add(h)
        unique_cols.append(col)

df = df[unique_cols]

In [296]:
df = pd.read_csv("../DataProcessed/hospital_billing_3_im.csv")
unique_sequences = df.drop_duplicates(subset=['sequence', 'result'])
label_counts = unique_sequences['result'].value_counts()
print(label_counts)

result
regular    73441
deviant     4084
Name: count, dtype: int64

In [178]:
# Get sequence-level labels
sequence_labels = df.groupby('sequence')['result'].first()

# Split into majority/minority sequences
majority = sequence_labels[sequence_labels == 'regular'].index
minority = sequence_labels[sequence_labels == 'deviant'].index

# Random under-sample from regular to match deviant count
np.random.seed(42)
sampled_seqs = np.random.choice(majority, size=len(minority), replace=False)

# Combine and filter df
balanced_sequences = np.concatenate([sampled_seqs, minority])
df_balanced = df[df['sequence'].isin(balanced_sequences)].copy()

In [293]:
df_balanced.to_csv("../DataProcessed/sepsis_cases_4_im.csv", index = False)

In [184]:
unique_sequences = df_balanced.drop_duplicates(subset=['sequence', 'result'])
label_counts = unique_sequences['result'].value_counts()
print(label_counts)

result
deviant    59013
regular    59013
Name: count, dtype: int64

In [170]:
# Convert numeric strings, leave others as-is
sc1 = pd.to_numeric(df['sc1'], errors='coerce')  # '193.0'→193.0, 'other'→NaN
df['sc1'] = np.where(
    sc1.notna(), 
    sc1.astype('Int64').astype(str),  # Convert valid numbers to int strings
    df['sc1']                         # Keep non-numeric strings
)

In [123]:
BPI12_dt['status'] = BPI12_dt['lifecycle:transition'].map(cycle_mapping)

In [122]:
transitions = list(np.sort(BPI12_dt['lifecycle:transition'].unique()))
cycle_mapping = {transition: letter for transition, letter in zip(transitions, string.ascii_lowercase)}

In [55]:
# First change NAN to preseve the orginal NAN as categorial
BPI_dt = BPI_dt.fillna('N')
# BPI12 set. Transform case:AMOUNT_REQ to integer 
if not BPI12_dt['case:AMOUNT_REQ'].isnull().any():
    BPI12_dt['case:AMOUNT_REQ'] = BPI12_dt['case:AMOUNT_REQ'].astype(int)

NameError: name 'BPI12_dt' is not defined

In [124]:
#BPI12/17 set
BPI12_dt['event'] = BPI12_dt['event_label'] + BPI12_dt['status']

In [97]:
# for helpdesk dataset
#BPI12_dt["extracted_index"] = BPI12_dt["case:variant"].str.extract(r'(\d+)').astype(int)
# Check if extracted index matches "case:variant-index"
#BPI12_dt["match"] = BPI12_dt["extracted_index"] == BPI12_dt["case:variant-index"]
# Check if all values match
#BPI12_dt["match"].all()

In [182]:
#BPI12_dt = BPI12_dt.drop(columns = ['lifecycle:transition', "concept:name"])
#BPI17set
#BPI12_dt = BPI12_dt.drop(columns = ['lifecycle:transition', "concept:name", 'pre_concept:name','full_concept:name'])
#BPI12set
BPI12_dt = BPI12_dt.drop(columns = ['lifecycle:transition', "concept:name", 'pre_concept:name','full_concept:name', "case:REG_DATE"])
#helpdesk set
#BPI12_dt = BPI12_dt.drop(columns = ['lifecycle:transition', "concept:name", "Activity", "Resource", "case:variant", "extracted_index", "match"])

In [184]:
# Columns to exclude from checking
exclude_cols = ["status", 'event', 'sequence', 'time', 'event_label']  

# Identify columns to drop, excluding specified ones
columns_to_drop = [col for col in BPI12_dt.columns if col not in exclude_cols and BPI12_dt[col].nunique() == 1]

# Drop those columns
BPI12_dt.drop(columns=columns_to_drop, inplace=True)

In [189]:
BPI12a = BPI12_dt.loc[BPI12_dt['event_label'].str.startswith('A')].copy()
BPI12o = BPI12_dt.loc[BPI12_dt['event_label'].str.startswith('O')].copy()
BPI12w = BPI12_dt.loc[BPI12_dt['event_label'].str.startswith('W')].copy()

In [190]:
BPI12a.to_csv("D:/Research in UAE/nextevent/output/BPI12ac.csv", index = False)
BPI12o.to_csv("D:/Research in UAE/nextevent/output/BPI12oc.csv", index = False)
BPI12w.to_csv("D:/Research in UAE/nextevent/output/BPI12wc.csv", index = False)

In [103]:
# mapping dictionaries BPI12 dataset
activity_mapping = {
    'A_ACCEPTED': "AA", 
    'A_ACTIVATED': "AB", 
    'A_APPROVED': "AC", 
    'A_CANCELLED': "AD",
    'A_DECLINED' : "AE", 
    'A_FINALIZED' : "AF", 
    'A_PARTLYSUBMITTED' :"AG", 
    'A_PREACCEPTED': "AH",
    'A_REGISTERED': "AI", 
    'A_SUBMITTED': "AJ", 
    'O_ACCEPTED': "OA", 
    'O_CANCELLED': "OB",
    'O_CREATED': "OC", 
    'O_DECLINED': "OD", 
    'O_SELECTED': "OE", 
    'O_SENT': "OF", 
    'O_SENT_BACK':"OG",
    'W_Afhandelen leads': "WA", 
    'W_Beoordelen fraude': "WB",
    'W_Completeren aanvraag':"WC", 
    'W_Nabellen incomplete dossiers': "WD",
    'W_Nabellen offertes': "WE", 
    'W_Valideren aanvraag': "WF",
    'W_Wijzigen contractgegevens': "WG"
    }